### PR TITLE
fix #155 return empty rows when query from information_schema.columns

### LINKED ISSUE #155: Need to return empty rows when query from `information_schema.columns`.
**What would you like to be added**:
Need to return empty rows when query from `information_schema.columns`, because it will cause incorrect mycli behavior.

image

**Why is this needed**:

### PR DESCRIPTION
**Pull request by Penglq**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #155 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by AlexStocks — APPROVED** [review]

**Review by dongzl — APPROVED** [review]

File: pkg/runtime/plan/simple_select.go [hunk 1]
```diff
@@ -67,6 +74,20 @@ func (s *SimpleQueryPlan) ExecIn(ctx context.Context, conn proto.VConn) (proto.R
...
 
+func (s *SimpleQueryPlan) filter() bool {
+	if len(s.Stmt.From) <= 0 {
+		return false
+	}
+	source, ok := s.Stmt.From[0].Source().(ast.TableName)
+	if !ok {
+		return false
+	}
+	if source.String() == "`information_schema`.`columns`" {
```
Comment (Lvnszn) [inline pkg/runtime/plan/simple_select.go:85]: return source.String() == "`information_schema`.`columns`"  会不会好点。

**Review by Lvnszn — APPROVED** [review]

**Review by jjeffcaii — APPROVED** [review]
