### PR TITLE
Feature: Support "show topology from xxx" fix: #249

### LINKED ISSUE #249: Feature: Support "show topology from xxx".
**What would you like to be added**:

**Why is this needed**:

Support "show topology from xxx", show sharding table  topology.

image

### PR DESCRIPTION
**Pull request by Penglq**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #249 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Review by dongzl — APPROVED** [review]

**Review by PangXing — APPROVED** [review]

File: pkg/runtime/plan/show_topology.go [hunk 1]
```diff
@@ -0,0 +1,125 @@
...
+		return nil, errors.WithStack(err)
+	}
+
+	table = sb.String()
+
+	fields := []proto.Field{
+		mysql.NewField("id", consts.FieldTypeVarString),
+		mysql.NewField("group_name", consts.FieldTypeVarString),
+		mysql.NewField("table_name", consts.FieldTypeVarString),
+	}
```
Comment (jjeffcaii) [inline pkg/runtime/plan/show_topology.go:84]: Move it into a global variable.

File: pkg/runtime/plan/show_topology.go [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+
+	ds := &dataset.VirtualDataset{
+		Columns: fields,
+	}
+
+	for logicalTable, v := range st.rule.VTables() {
```
Comment (jjeffcaii) [inline pkg/runtime/plan/show_topology.go:90]: Use `st.rule.VTable(table)` instead.

**Review by jjeffcaii — APPROVED** [review]
LGTM

**Review by AlexStocks — APPROVED** [review]
