### PR TITLE
fix: #228

### LINKED ISSUE #228: Title of show tables is unreasonable
**What happened**:
Using ”use employees; show table“， the title is “Tables_in_employees_0000”.

image

**What you expected to happen**:
I think it should be "Tables_in_employees".

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by Penglq**
**What this PR does**:

**Which issue(s) this PR fixes**:

Fixes #228 .

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

File: pkg/runtime/plan/show_tables.go [hunk 1]
```diff
@@ -20,6 +20,7 @@ package plan
 import (
 	"context"
 	"database/sql"
+	rcontext "github.com/arana-db/arana/pkg/runtime/context"
```
Comment (dongzl) [inline pkg/runtime/plan/show_tables.go:23]: format import.

File: pkg/runtime/plan/show_tables.go [hunk 2]
```diff
@@ -28,6 +29,7 @@ import (
 )
 
 import (
+	cMysql "github.com/arana-db/arana/pkg/constants/mysql"
```
Comment (dongzl) [inline pkg/runtime/plan/show_tables.go:32]: `cMysql` is not a good name, how about `constant` directly?

**Review by dongzl — CHANGES_REQUESTED** [review]

**Review by dongzl — APPROVED** [review]

**Review by jjeffcaii — APPROVED** [review]
LGTM

**Review by Lvnszn — APPROVED** [review]

**Review by AlexStocks — APPROVED** [review]
